2024-08-19 15:41:54.085 [info] Experiment 'pythonCreateEnvOnPipInstall' is active
2024-08-19 15:41:54.085 [info] Experiment 'pythonRecommendTensorboardExt' is active
2024-08-19 15:41:54.085 [info] Experiment 'pythonTerminalEnvVarActivation' is active
2024-08-19 15:41:54.085 [info] Experiment 'pythonTestAdapter' is active
2024-08-19 15:41:54.085 [error] Reading directory to watch failed [Error: ENOENT: no such file or directory, scandir '/root/.pixi/envs'
	at Object.readdirSync (node:fs:1515:26)
	at /root/.local/share/code-server/extensions/ms-python.python-2024.12.3-universal/out/client/extension.js:2:586747
	at /root/.local/share/code-server/extensions/ms-python.python-2024.12.3-universal/out/client/extension.js:2:586938
	at Array.map (<anonymous>)
	at d.initWatchers (/root/.local/share/code-server/extensions/ms-python.python-2024.12.3-universal/out/client/extension.js:2:586656)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async d.ensureWatchersReady (/root/.local/share/code-server/extensions/ms-python.python-2024.12.3-universal/out/client/extension.js:2:543067)] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/root/.pixi/envs'
}
2024-08-19 15:41:54.085 [error] Dir "/root/.pixi/envs" is not watchable (directory does not exist)
2024-08-19 15:41:54.269 [info] Default formatter is set to null for workspace /root/
2024-08-19 15:41:54.273 [info] Starting Environment refresh
2024-08-19 15:41:54.273 [info] Searching for interpreters in posix paths locator
2024-08-19 15:41:54.276 [info] Searching for pyenv environments
2024-08-19 15:41:54.276 [info] Searching for conda environments
2024-08-19 15:41:54.276 [info] Searching for global virtual environments
2024-08-19 15:41:54.276 [info] Searching for custom virtual environments
2024-08-19 15:41:54.293 [info] pyenv is not installed
2024-08-19 15:41:54.293 [info] Finished searching for pyenv environments: 19 milliseconds
2024-08-19 15:41:54.293 [info] Finished searching for custom virtual envs: 19 milliseconds
2024-08-19 15:41:54.296 [info] > conda info --json
2024-08-19 15:41:54.298 [info] > pixi --version
2024-08-19 15:41:54.298 [error] [Error: spawn pixi ENOENT
	at ChildProcess._handle.onexit (node:internal/child_process:286:19)
	at onErrorNT (node:internal/child_process:484:16)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn pixi',
  path: 'pixi',
  spawnargs: [ '--version' ]
}
2024-08-19 15:41:54.299 [info] > hatch env show --json
2024-08-19 15:41:54.299 [info] cwd: .
2024-08-19 15:41:54.303 [info] > pyenv which python
2024-08-19 15:41:54.303 [info] cwd: .
2024-08-19 15:41:54.303 [info] Finished searching for global virtual envs: 29 milliseconds
2024-08-19 15:41:54.306 [info] Found: /bin/python3 --> /bin/python3.11
2024-08-19 15:41:54.345 [info] Found: /bin/python3.11 --> /bin/python3.11
2024-08-19 15:41:54.362 [info] Found: /usr/bin/python3 --> /usr/bin/python3.11
2024-08-19 15:41:54.362 [info] Found: /usr/bin/python3.11 --> /usr/bin/python3.11
2024-08-19 15:41:54.454 [info] Found: /usr/local/bin/python --> /usr/local/bin/python3.12
2024-08-19 15:41:54.454 [info] Found: /usr/local/bin/python3 --> /usr/local/bin/python3.12
2024-08-19 15:41:54.454 [info] Found: /usr/local/bin/python3.12 --> /usr/local/bin/python3.12
2024-08-19 15:41:54.742 [info] > /bin/python3 -I ..local/share/code-server/extensions/ms-python.python-2024.12.3-universal/python_files/get_output_via_markers.py ..local/share/code-server/extensions/ms-python.python-2024.12.3-universal/python_files/interpreterInfo.py
2024-08-19 15:41:54.753 [info] Finished searching for interpreters in posix paths locator: 477 milliseconds
2024-08-19 15:41:54.753 [info] > /usr/bin/python3 -I ..local/share/code-server/extensions/ms-python.python-2024.12.3-universal/python_files/get_output_via_markers.py ..local/share/code-server/extensions/ms-python.python-2024.12.3-universal/python_files/interpreterInfo.py
2024-08-19 15:41:54.755 [info] Environments refresh paths discovered (event): 483 milliseconds
2024-08-19 15:41:54.755 [info] Environments refresh paths discovered: 483 milliseconds
2024-08-19 15:41:54.953 [info] > /usr/local/bin/python -I ..local/share/code-server/extensions/ms-python.python-2024.12.3-universal/python_files/get_output_via_markers.py ..local/share/code-server/extensions/ms-python.python-2024.12.3-universal/python_files/interpreterInfo.py
2024-08-19 15:41:55.256 [info] Environments refresh finished (event): 984 milliseconds
2024-08-19 15:41:55.265 [info] Environment refresh took 992 milliseconds
2024-08-19 15:41:55.266 [warning] could not find a pixi interpreter for the interpreter at /usr/local/bin/python
2024-08-19 15:41:55.268 [info] Python interpreter path: /usr/local/bin/python
2024-08-19 15:41:56.344 [info] Shell integration status changed, can confirm it's working.
2024-08-19 15:41:56.346 [warning] could not find a pixi interpreter for the interpreter at /usr/local/bin/python
2024-08-19 15:41:56.473 [info] Starting Jedi language server for root.
2024-08-19 15:41:56.897 [warning] could not find a pixi interpreter for the interpreter at /usr/local/bin/python
